name: Databricks CI/CD

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:
  ci:
    name: CI - Validate Bundle
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}

    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.221.0

      - name: Validate bundle (dev)
        run: |
          databricks bundle validate --target dev \
            --var="catalog=surakshadb" \
            --var="pipeline_schema=db_stg"

  deploy-dev:
    name: CD - Deploy Dev
    needs: ci
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}

    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.221.0

      - name: Deploy to Dev
        run: |
          databricks bundle deploy --target dev \
            --var="catalog=surakshadb" \
            --var="pipeline_schema=db_stg"
