name: Databricks CI/CD

on:
  pull_request:
    branches: [ main ]

  push:
    branches: 
      - main
      - feature/*
      - sdl_IT


jobs:
  ci:
    name: CI - Validate Bundle
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}

    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.221.0

      - name: Validate Dev Target
        run: databricks bundle validate --target dev

      - name: Validate Prod Target
        run: databricks bundle validate --target prod


  deploy-dev:
    name: CD - Deploy Dev
    needs: ci
    
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/feature/') || github.ref == 'refs/heads/sdl_IT')
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}

    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.221.0

      - name: Deploy to Dev
        run: databricks bundle deploy --target dev


  deploy-prod:
    name: CD - Deploy Prod
    needs: ci

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }} 
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}

    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.221.0

      - name: Deploy to Prod
        run: databricks bundle deploy --target prod